services:
  bmad-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bmad-knowledge-bot:latest
    container_name: bmad-discord-bot
    #restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Volume mounts
    volumes:
      # Optional: Mount logs directory for persistent logging
      - ./logs:/app/logs:rw
      # Mount data directory for SQLite database persistence (when using SQLite)
      - ./data:/app/data:rw
    
    # Uncomment the following line when using MySQL database
    # depends_on:
    #   - mysql
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false  # Set to false to allow database and log file writes
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "/app/main", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # MySQL Database Service (optional, for cloud-native deployments)
  # Uncomment this entire service when using MySQL instead of SQLite
  # mysql:
  #   image: mysql:8.0
  #   container_name: bmad-mysql
  #   restart: unless-stopped
  #   
  #   # Environment variables for MySQL configuration
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-changeme}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE:-bmad_bot}
  #     MYSQL_USER: ${MYSQL_USERNAME:-bmad_user}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD:-changeme}
  #   
  #   # Volume for persistent MySQL data
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #     - ./mysql/init:/docker-entrypoint-initdb.d:ro
  #   
  #   # MySQL port (internal only, not exposed to host by default)
  #   # ports:
  #   #   - "3306:3306"  # Uncomment to expose MySQL port to host
  #   
  #   # Security settings
  #   security_opt:
  #     - no-new-privileges:true
  #   
  #   # Resource limits
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: '1.0'
  #       reservations:
  #         memory: 512M
  #         cpus: '0.5'
  #   
  #   # Health check
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_PASSWORD:-changeme}"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 30s
  #   
  #   # Logging configuration
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "50m"
  #       max-file: "3"

# Volumes for persistent data (uncomment when using MySQL)
# volumes:
#   mysql_data:
#     driver: local
