apiVersion: v1
kind: ConfigMap
metadata:
  name: bmad-bot-config
  namespace: bmad-bot
  labels:
    app: bmad-discord-bot
    component: config
data:
  # Database Configuration (MySQL-only as per Story 2.12) 
  # Note: Sensitive credentials (username, password, host) are in secrets
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "bmad_bot"
  MYSQL_TIMEOUT: "30s"
  
  # AI Provider Configuration (Ollama only as per Story 2.11)
  AI_PROVIDER: "ollama"
  OLLAMA_MODEL: "devstral"
  OLLAMA_TIMEOUT: "30"
  OLLAMA_QUALITY_MONITORING_ENABLED: "true"
  OLLAMA_PROMPT_STYLE: "structured"
  
  # AI Rate Limiting Configuration
  AI_PROVIDER_OLLAMA_RATE_LIMIT_PER_MINUTE: "60"
  AI_PROVIDER_RATE_LIMIT_PER_MINUTE: "60"
  AI_PROVIDER_OLLAMA_RATE_LIMIT_PER_DAY: "2000"
  AI_PROVIDER_RATE_LIMIT_PER_DAY: "2000"
  AI_PROVIDER_OLLAMA_WARNING_THRESHOLD: "0.8"
  AI_PROVIDER_WARNING_THRESHOLD: "0.8"
  AI_PROVIDER_OLLAMA_THROTTLED_THRESHOLD: "0.9"
  AI_PROVIDER_THROTTLED_THRESHOLD: "0.9"
  
  # Message Processing Configuration
  MESSAGE_RECOVERY_WINDOW_MINUTES: "5"
  
  # Reply Mention Configuration
  REPLY_MENTION_DELETE_MESSAGE: "false"
  
  # Reaction Trigger Configuration
  REACTION_TRIGGER_ENABLED: "false"
  REACTION_TRIGGER_EMOJI: "🤖"
  REACTION_TRIGGER_APPROVED_USER_IDS: ""
  REACTION_TRIGGER_APPROVED_ROLE_NAMES: ""
  REACTION_TRIGGER_REQUIRE_REACTION: "true"
  REACTION_TRIGGER_REMOVE_REACTION: "true"
  
  # Forum Channel Configuration (Story 2.14)
  MONITORED_FORUM_CHANNELS: "1400600574038114395"
  
  # Knowledge Base Configuration
  BMAD_KB_REFRESH_ENABLED: "true"
  BMAD_KB_REFRESH_INTERVAL_HOURS: "6"
  BMAD_KB_REMOTE_URL: "https://github.com/bmadcode/BMAD-METHOD/raw/refs/heads/main/bmad-core/data/bmad-kb.md"
  
  # Bot Status Configuration
  BMAD_STATUS_ROTATION_ENABLED: "true"
  BMAD_STATUS_ROTATION_INTERVAL: "5m"
  BOT_STATUS_UPDATE_ENABLED: "false"
  BOT_STATUS_UPDATE_INTERVAL: "10"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"