apiVersion: v1
kind: ServiceAccount
metadata:
  name: bmad-bot-sa
  namespace: bmad-bot
  labels:
    app: bmad-discord-bot
    component: serviceaccount
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: bmad-bot-role
  namespace: bmad-bot
  labels:
    app: bmad-discord-bot
    component: rbac
rules:
# Minimal permissions - bot doesn't need any special Kubernetes API access
# This role exists for future extensibility if needed
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bmad-bot-rolebinding
  namespace: bmad-bot
  labels:
    app: bmad-discord-bot
    component: rbac
subjects:
- kind: ServiceAccount
  name: bmad-bot-sa
  namespace: bmad-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bmad-bot-role